### ISSUE TITLE
[Firefox] Doesn't work

### ISSUE THREAD

**Issue by heubergen** [james-fray/local-cdn#14]
As you're add-on is now also available in the AMO i tested it at it seems not to work.

STR:
1) Install Local CDN from https://addons.mozilla.org/en-US/firefox/addon/local-cdn-webextension/
2) Open https://decentraleyes.org/test/

**Comment by james-fray** [comment]
I just removed Local CDN from AMO website. Firefox has a core bug that prevents redirection to take place. Until this bug is fixed, the listing will be hidden.

> Open https://decentraleyes.org/test/

This is not a good way to check this extension. You need to check network tab and make sure libraries are redirected.

**Comment by heubergen** [comment]
Thanks for the information and sorry for the missing information (e.g. firefox version, windows etc.) I was a little in a rush.
If you have any bug ticket # may I can help to prioritize it :)

**Comment by james-fray** [comment]
Here you go:

https://bugzilla.mozilla.org/show_bug.cgi?id=1256122
https://bugzilla.mozilla.org/show_bug.cgi?id=1257781

**Comment by james-fray** [comment]
This seems to be fixed on FF57! Local CDN is back
