### ISSUE TITLE
I want local CDN firefox version！！！

### ISSUE THREAD

**Issue by yunluo** [james-fray/local-cdn#15]
I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！I want local CDN firefox version！！！

**Comment by james-fray** [comment]
It is available for FF 57; https://addons.mozilla.org/firefox/addon/local-cdn-webextension/
