### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by coeligena** [james-fray/local-cdn#2]
chrome-extension://dgfedofdiaapcideaajjaklpmdpcdapg/data/resources/angularjs/1.3.13/angular.min.js.dec

This request gives an error like "Your file was not found", and I checked it doesn't exist in the resources folder. I assume so the code doesn't check whether the resource cache exists or not. I assume it should allow the request to bypass and may even collect some information to include those missing in the next release.

**Comment by schomery** [comment]
Thanks for the report. We do have a validator but there was something wrong with it. It should be fine in 0.1.1

> may even collect some information to include those missing in the next release.

This might violate user privacy so for now lets add libraries based on user reports.
