### ISSUE TITLE
Is there any relation between this and LocalCDN by nobody42?

### ISSUE THREAD

**Issue by ahydronous** [james-fray/local-cdn#25]
Its this extension: https://addons.mozilla.org/en-US/firefox/addon/localcdn-fork-of-decentraleyes/

Also see: https://addons.mozilla.org/en-US/firefox/addon/localcdn-fork-of-decentraleyes/ and https://codeberg.org/nobody/LocalCDN

**Comment by JReming85** [comment]
Yes, that one is getting updated.  This repo hasnt been changed since 2017
