### ISSUE TITLE
conflict wth HTTPS Everywhere

### ISSUE THREAD

**Issue by noblepirate** [james-fray/local-cdn#3]
Warning:
This extension failed to redirect a network request to https://yandex.st/jquery/1.8.3/jquery.min.js because another extension (Local CDN) redirected it to chrome-extension://dgfedofdiaapcideaajjaklpmdpcdapg/data/resources/jquery/1.8.3/jquery.min.js.dec

**Comment by james-fray** [comment]
See https://github.com/james-fray/local-cdn/issues/1
