### ISSUE TITLE
Support "jQuery-version.js"

### ISSUE THREAD

**Issue by kurtextrem** [james-fray/local-cdn#5]
Some sites have "jquery-1.2.3.min.js" or "jquery.123.min.js" in their name.

Also, maybe as an experimental feature: When a site tries to load "jquery.min.js", always use the latest version? (could break sites, but could also "upgrade" sites, as jQ releases tend to contain perf improvements)

**Comment by james-fray** [comment]
> Some sites have "jquery-1.2.3.min.js" or "jquery.123.min.js" in their name.

Can you provide an example site 

> maybe as an experimental feature: When a site tries to load "jquery.min.js"

You mean from a known CDN or any url that ends with "jquery.min.js"? I am asking this as all the supported CDN websites have version number in their URLs.

**Comment by kurtextrem** [comment]
For the first one, no. But I suspect it would work anyway.

I mean any url that ends with jquery.min.js, without having a version string in the url.

**Comment by james-fray** [comment]
> I mean any url that ends with jquery.min.js, without having a version string in the url.

Not a good idea from technical point of view. So basically Local CDN adds an HTTP observer once it is loaded. currently we add this observer only on the supported domains (those CDN hostings that are listed in the FAQs page), if we want to do this "ends with" check we are going to extend this observer from a set of URLs to all urls and hence this has effects on every HTTP request that browser makes. As you can see the drawback is huge. Currently Local CDN bypasses all urls except those that are from known CDNs and hence it does not affect your browser performance at all.

**Comment by kurtextrem** [comment]
Sounds true.
